// @HEADER
// *****************************************************************************
//             Xpetra: A linear algebra interface package
//
// Copyright 2012 NTESS and the Xpetra contributors.
// SPDX-License-Identifier: BSD-3-Clause
// *****************************************************************************
// @HEADER

#ifndef XPETRA_EXPORT_HPP
#define XPETRA_EXPORT_HPP

/* this file is automatically generated - do not edit (see script/interfaces.py) */

#include <Tpetra_KokkosCompat_DefaultNode.hpp>
#include <Teuchos_Describable.hpp>
#include <Teuchos_as.hpp>
#include "Xpetra_Map.hpp"
#include <iterator>

namespace Xpetra {

template <class LocalOrdinal,
          class GlobalOrdinal,
          class Node = Tpetra::KokkosClassic::DefaultNode::DefaultNodeType>
using Export = Tpetra::Export<LocalOrdinal, GlobalOrdinal, Node>;
}  // namespace Xpetra

#define XPETRA_EXPORT_SHORT
#endif  // XPETRA_EXPORT_HPP
