#include <KokkosCompat_ClassicNodeAPI_Wrapper.hpp>
#include <Kokkos_AnonymousSpace.hpp>
#include <Kokkos_Concepts.hpp>
#include <Kokkos_DualView.hpp>
#include <Kokkos_HostSpace.hpp>
#include <Kokkos_Layout.hpp>
#include <Kokkos_ScratchSpace.hpp>
#include <Kokkos_Serial.hpp>
#include <Kokkos_View.hpp>
#include <Teuchos_Array.hpp>
#include <Teuchos_ArrayRCPDecl.hpp>
#include <Teuchos_ArrayViewDecl.hpp>
#include <Teuchos_BLAS_types.hpp>
#include <Teuchos_Comm.hpp>
#include <Teuchos_DataAccess.hpp>
#include <Teuchos_ENull.hpp>
#include <Teuchos_FancyOStream.hpp>
#include <Teuchos_ParameterList.hpp>
#include <Teuchos_PtrDecl.hpp>
#include <Teuchos_RCPDecl.hpp>
#include <Teuchos_RCPNode.hpp>
#include <Teuchos_Range1D.hpp>
#include <Teuchos_VerbosityLevel.hpp>
#include <Tpetra_Access.hpp>
#include <Tpetra_Details_WrappedDualView.hpp>
#include <Tpetra_MultiVector_decl.hpp>
#include <Tpetra_Operator.hpp>
#include <Tpetra_RowGraph_decl.hpp>
#include <Tpetra_RowMatrix_decl.hpp>
#include <Tpetra_Vector_decl.hpp>
#include <impl/Kokkos_SharedAlloc.hpp>
#include <impl/Kokkos_ViewCtor.hpp>
#include <impl/Kokkos_ViewMapping.hpp>
#include <iterator>
#include <memory>
#include <sstream> // __str__
#include <string>
#include <vector>

#include <functional>
#include <pybind11/pybind11.h>
#include <string>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <Teuchos_RCP.hpp>


#ifndef BINDER_PYBIND11_TYPE_CASTER
	#define BINDER_PYBIND11_TYPE_CASTER
	PYBIND11_DECLARE_HOLDER_TYPE(T, Teuchos::RCP<T>)
	PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>)
	PYBIND11_DECLARE_HOLDER_TYPE(T, T*)
	PYBIND11_MAKE_OPAQUE(std::shared_ptr<void>)
#endif

void bind_Tpetra_RowMatrix_decl(std::function< pybind11::module &(std::string const &namespace_) > &M)
{
	{ // Tpetra::RowMatrix file:Tpetra_RowMatrix_decl.hpp line:85
		pybind11::class_<Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>, Teuchos::RCP<Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>>, Tpetra::SrcDistObject, Tpetra::Packable<char,int>> cl(M("Tpetra"), "RowMatrix_double_int_long_long_Kokkos_Compat_KokkosDeviceWrapperNode_Kokkos_Serial_Kokkos_HostSpace_t", "");
		cl.def("getComm", (class Teuchos::RCP<const class Teuchos::Comm<int> > (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getComm, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getComm() const --> class Teuchos::RCP<const class Teuchos::Comm<int> >");
		cl.def("getRowMap", (class Teuchos::RCP<const class Tpetra::Map<int, long long> > (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getRowMap, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getRowMap() const --> class Teuchos::RCP<const class Tpetra::Map<int, long long> >");
		cl.def("getColMap", (class Teuchos::RCP<const class Tpetra::Map<int, long long> > (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getColMap, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getColMap() const --> class Teuchos::RCP<const class Tpetra::Map<int, long long> >");
		cl.def("getGraph", (class Teuchos::RCP<const class Tpetra::RowGraph<int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > > (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getGraph, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getGraph() const --> class Teuchos::RCP<const class Tpetra::RowGraph<int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > >");
		cl.def("getGlobalNumRows", (unsigned long (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getGlobalNumRows, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getGlobalNumRows() const --> unsigned long");
		cl.def("getGlobalNumCols", (unsigned long (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getGlobalNumCols, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getGlobalNumCols() const --> unsigned long");
		cl.def("getLocalNumRows", (unsigned long (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalNumRows, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalNumRows() const --> unsigned long");
		cl.def("getLocalNumCols", (unsigned long (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalNumCols, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalNumCols() const --> unsigned long");
		cl.def("getIndexBase", (long long (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getIndexBase, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getIndexBase() const --> long long");
		cl.def("getGlobalNumEntries", (unsigned long (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getGlobalNumEntries, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getGlobalNumEntries() const --> unsigned long");
		cl.def("getLocalNumEntries", (unsigned long (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalNumEntries, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalNumEntries() const --> unsigned long");
		cl.def("getNumEntriesInGlobalRow", (unsigned long (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)(long long) const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getNumEntriesInGlobalRow, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getNumEntriesInGlobalRow(long long) const --> unsigned long", pybind11::arg("globalRow"));
		cl.def("getNumEntriesInLocalRow", (unsigned long (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)(int) const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getNumEntriesInLocalRow, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getNumEntriesInLocalRow(int) const --> unsigned long", pybind11::arg("localRow"));
		cl.def("getGlobalMaxNumRowEntries", (unsigned long (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getGlobalMaxNumRowEntries, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getGlobalMaxNumRowEntries() const --> unsigned long");
		cl.def("getLocalMaxNumRowEntries", (unsigned long (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalMaxNumRowEntries, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalMaxNumRowEntries() const --> unsigned long");
		cl.def("hasColMap", (bool (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::hasColMap, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::hasColMap() const --> bool");
		cl.def("isLocallyIndexed", (bool (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::isLocallyIndexed, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::isLocallyIndexed() const --> bool");
		cl.def("isGloballyIndexed", (bool (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::isGloballyIndexed, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::isGloballyIndexed() const --> bool");
		cl.def("isFillComplete", (bool (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::isFillComplete, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::isFillComplete() const --> bool");
		cl.def("supportsRowViews", (bool (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::supportsRowViews, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::supportsRowViews() const --> bool");
		cl.def("getLocalDiagCopy", (void (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)(class Tpetra::Vector<double, int, long long> &) const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalDiagCopy, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getLocalDiagCopy(class Tpetra::Vector<double, int, long long> &) const --> void", pybind11::arg("diag"));
		cl.def("leftScale", (void (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)(const class Tpetra::Vector<double, int, long long> &)) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::leftScale, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::leftScale(const class Tpetra::Vector<double, int, long long> &) --> void", pybind11::arg("x"));
		cl.def("rightScale", (void (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)(const class Tpetra::Vector<double, int, long long> &)) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::rightScale, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::rightScale(const class Tpetra::Vector<double, int, long long> &) --> void", pybind11::arg("x"));
		cl.def("getFrobeniusNorm", (double (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)() const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getFrobeniusNorm, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::getFrobeniusNorm() const --> double");
		cl.def("add", [](Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>> const &o, const double & a0, const class Tpetra::RowMatrix<double, int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > & a1, const double & a2) -> Teuchos::RCP<class Tpetra::RowMatrix<double, int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > > { return o.add(a0, a1, a2); }, "", pybind11::arg("alpha"), pybind11::arg("A"), pybind11::arg("beta"));
		cl.def("add", [](Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>> const &o, const double & a0, const class Tpetra::RowMatrix<double, int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > & a1, const double & a2, const class Teuchos::RCP<const class Tpetra::Map<int, long long> > & a3) -> Teuchos::RCP<class Tpetra::RowMatrix<double, int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > > { return o.add(a0, a1, a2, a3); }, "", pybind11::arg("alpha"), pybind11::arg("A"), pybind11::arg("beta"), pybind11::arg("domainMap"));
		cl.def("add", [](Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>> const &o, const double & a0, const class Tpetra::RowMatrix<double, int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > & a1, const double & a2, const class Teuchos::RCP<const class Tpetra::Map<int, long long> > & a3, const class Teuchos::RCP<const class Tpetra::Map<int, long long> > & a4) -> Teuchos::RCP<class Tpetra::RowMatrix<double, int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > > { return o.add(a0, a1, a2, a3, a4); }, "", pybind11::arg("alpha"), pybind11::arg("A"), pybind11::arg("beta"), pybind11::arg("domainMap"), pybind11::arg("rangeMap"));
		cl.def("add", (class Teuchos::RCP<class Tpetra::RowMatrix<double, int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > > (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)(const double &, const class Tpetra::RowMatrix<double, int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > &, const double &, const class Teuchos::RCP<const class Tpetra::Map<int, long long> > &, const class Teuchos::RCP<const class Tpetra::Map<int, long long> > &, const class Teuchos::RCP<class Teuchos::ParameterList> &) const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::add, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::add(const double &, const class Tpetra::RowMatrix<double, int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > &, const double &, const class Teuchos::RCP<const class Tpetra::Map<int, long long> > &, const class Teuchos::RCP<const class Tpetra::Map<int, long long> > &, const class Teuchos::RCP<class Teuchos::ParameterList> &) const --> class Teuchos::RCP<class Tpetra::RowMatrix<double, int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > >", pybind11::arg("alpha"), pybind11::arg("A"), pybind11::arg("beta"), pybind11::arg("domainMap"), pybind11::arg("rangeMap"), pybind11::arg("params"));
		cl.def("pack", (void (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)(const class Teuchos::ArrayView<const int> &, class Teuchos::Array<char> &, const class Teuchos::ArrayView<unsigned long> &, unsigned long &) const) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::pack, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::pack(const class Teuchos::ArrayView<const int> &, class Teuchos::Array<char> &, const class Teuchos::ArrayView<unsigned long> &, unsigned long &) const --> void", pybind11::arg("exportLIDs"), pybind11::arg("exports"), pybind11::arg("numPacketsPerLID"), pybind11::arg("constantNumPackets"));
		cl.def("assign", (class Tpetra::RowMatrix<double, int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > & (Tpetra::RowMatrix<double,int,long long,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>::*)(const class Tpetra::RowMatrix<double, int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > &)) &Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::operator=, "C++: Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::operator=(const class Tpetra::RowMatrix<double, int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > &) --> class Tpetra::RowMatrix<double, int, long long, class Kokkos::Compat::KokkosDeviceWrapperNode<class Kokkos::Serial, class Kokkos::HostSpace> > &", pybind11::return_value_policy::automatic, pybind11::arg(""));
		cl.def("pack", (void (Tpetra::Packable<char,int>::*)(const class Teuchos::ArrayView<const int> &, class Teuchos::Array<char> &, const class Teuchos::ArrayView<unsigned long> &, unsigned long &) const) &Tpetra::Packable<char, int>::pack, "C++: Tpetra::Packable<char, int>::pack(const class Teuchos::ArrayView<const int> &, class Teuchos::Array<char> &, const class Teuchos::ArrayView<unsigned long> &, unsigned long &) const --> void", pybind11::arg("exportLIDs"), pybind11::arg("exports"), pybind11::arg("numPacketsPerLID"), pybind11::arg("constantNumPackets"));
		cl.def("assign", (class Tpetra::Packable<char, int> & (Tpetra::Packable<char,int>::*)(const class Tpetra::Packable<char, int> &)) &Tpetra::Packable<char, int>::operator=, "C++: Tpetra::Packable<char, int>::operator=(const class Tpetra::Packable<char, int> &) --> class Tpetra::Packable<char, int> &", pybind11::return_value_policy::automatic, pybind11::arg(""));
	}
}
