# This file is automatically generated by xpetra/src/Utils/ExplicitInstantiation/genClassLists.sh
APPEND_SET(XPETRA_MULTIVECTOR_ETI_CLASSES Xpetra::MapExtractor )
APPEND_SET(XPETRA_MULTIVECTOR_ETI_CLASSES Xpetra::BlockedMultiVector )
APPEND_SET(XPETRA_MULTIVECTOR_ETI_CLASSES Xpetra::BlockedVector )
